// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $ExpandableDescription from "./islands/ExpandableDescription.tsx";
import * as $OpenEmail from "./islands/OpenEmail.tsx";
import * as $Project from "./islands/Project.tsx";
import * as $TechStack from "./islands/TechStack.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ExpandableDescription.tsx": $ExpandableDescription,
    "./islands/OpenEmail.tsx": $OpenEmail,
    "./islands/Project.tsx": $Project,
    "./islands/TechStack.tsx": $TechStack,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
